# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RosAvtoDengi' do

pod "AKPickerView"
pod "AFNetworking", "~> 2.0"
pod 'Motis', '~>1.3.0'

end

target 'RosAvtoDengiTests' do

end

target 'RosAvtoDengiUITests' do

end

