# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RosAvtoDengi' do

pod "AKPickerView"

end

target 'RosAvtoDengiTests' do

end

target 'RosAvtoDengiUITests' do

end

